services:
  - type: web
    name: graphic-audition
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn graphic_audition.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: DEFAULT_FROM_EMAIL
        value: graphicauditions@gmail.com
      - key: CONTACT_RECEIVER_EMAIL
        value: graphicauditions@gmail.com
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
