services:
  - type: web
    name: graphic-audition
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn graphic_audition.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: graphicaudition@gmail.com
      - key: DEFAULT_FROM_EMAIL
        value: graphicaudition@gmail.com
      - key: CONTACT_RECEIVER_EMAIL
        value: graphicaudition@gmail.com
